#
#   IMPORTANT: this file is whitespace sensitive. Use two spaces instead of tabs
#

permalink: /browse/by_topic/:categories/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md"]

title: UKGovLDWG

# HOME_PATH: "" # for local development
HOME_PATH: "http://swirrl.github.io/ukgovldwg-test" # for deployment

BRAND_COLOUR: coral
BRAND_COLOUR_LIGHT: "#fff3ef"